spring:
  cloud:
    config:
      server:
        git:
          uri:  http://xxx/config-repo.git
          skipSslValidation: true
          timeout: 20
          username: xxx
          password: xxx
server:
  port: 8888